# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import portrait_pb2 as portrait__pb2


class PortraitBackendStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Portrait = channel.unary_unary(
        '/portrait.PortraitBackend/Portrait',
        request_serializer=portrait__pb2.PortraitRequest.SerializeToString,
        response_deserializer=portrait__pb2.PortraitResponse.FromString,
        )


class PortraitBackendServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Portrait(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PortraitBackendServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Portrait': grpc.unary_unary_rpc_method_handler(
          servicer.Portrait,
          request_deserializer=portrait__pb2.PortraitRequest.FromString,
          response_serializer=portrait__pb2.PortraitResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'portrait.PortraitBackend', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
